### ISSUE TITLE
javassist.NotFoundException: org.tinymediamanager.license.Nul

### ISSUE THREAD

**Issue by zhaoyibo** [XanderYe/tmm-cracker#3]
v4.2.4 这个版本失效了
报错 javassist.NotFoundException: org.tinymediamanager.license.Nul

解包发现现在连 org.tinymediamanager.license 这个包都没了

![image](https://user-images.githubusercontent.com/11988080/145676845-6332b1cb-0451-43a7-acf3-cac6795518ba.png)

**Comment by hkthomas** [comment]
俺也一样。

**Comment by XanderYe** [comment]
Mac吗 MacOS下不区分大小写，文件名重复覆盖了

**Comment by hkthomas** [comment]
新年好。

用的Debian x64，试了一下，旧版本可以，不会报错。
